id: A88386BB3
title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
type: translation
pechas:
- I33BBD44B
- I46CCADAC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:50.975876
  last_modified_at: 2023-01-04 11:55:50.975883
  collections:
  - Gampopa Series
  - Works of Tibetan Masters
alignment_to_base:
  I33BBD44B/799F: 066F
  I46CCADAC/AECE: 066F
